#!/bin/bash

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

module add seas-lab-vorobeychik
# module add gcc-6.5.0

# matlab -nodisplay -nodesktop -r "addpath('model');addpath('data'); baseline; exit;"

# python main.py -t localnews -i MCMC
SEED=$1

matlab -nodisplay -nodesktop -r "addpath('data');addpath('model');SEED=${SEED};baseline; exit;"

Rscript --vanilla data/ife.R $SEED 0
Rscript --vanilla data/ife.R $SEED 10
Rscript --vanilla data/measures.R $SEED

# matlab -nodisplay -nodesktop -r "hmc_sample_chain(${chain}); exit;"

# matlab -nodisplay -nodesktop -r "addpath('model');plotmarginalizeddrift; exit;"
