#!/bin/bash

mkdir -p data/synthetic
mkdir -p results
# bsub -R 'span[hosts=1]' -G SEAS-Lab-Garnett -J "localnews" -o localnews.log "./onerun"

# bsub -R 'span[hosts=1]' -G SEAS-Lab-Garnett -J "tunesynthetic" -o tunesynthetic.log "./onerun"

# declare -a chains=(1 2 3 4 5)

# for chain in ${chains[@]}; do
#     bsub -R 'span[hosts=1]' -G SEAS-Lab-Garnett -J "synthetic_${chain}" -o "synthetic_${chain}".log "./onerun $chain"
# done

MAXSEED=25
declare -a ULS=(1 21 42)
declare -a RHOS=(0.2 0.5 0.8)

# MAXSEED=1
# declare -a ULS=(21)
# declare -a RHOS=(0.8)

if [ $1 = "run" ]
then
    for SEED in $(seq 1 1 $MAXSEED); do
        for uls in ${ULS[@]}; do
            for rho in ${RHOS[@]}; do
                bsub -R 'span[hosts=1]' -G SEAS-Lab-Garnett -J "s${SEED}uls${uls}rho${rho}" "./onerun $SEED $uls $rho"
            done
        done
    done
elif [ $1 = "posttrain" ]
then
    for uls in ${ULS[@]}; do
        for rho in ${RHOS[@]}; do
            Rscript --vanilla data/measures.R $MAXSEED $uls $rho
        done
    done
fi

# bsub -R 'span[hosts=1]' -G SEAS-Lab-Garnett -J "marginalize drift" -o marginalizedrift.log "./onerun"
