#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

module add seas-anaconda3

SEED=$1
DATA_NAME=$2
MODEL_NAME=$3

if [ $3 = 'ours' ]
then
    matlab -nodisplay -nodesktop -r "review_non_normal_error(${SEED},21,0.9,0.1,${DATA_NAME}); exit;"
elif [ $3 = "others" ]
then
    Rscript --vanilla bgsc.R ${DATA_NAME} "rho_09_uls_21_effect_01_SEED_${SEED}"
    Rscript --vanilla ife.R ${DATA_NAME} "rho_09_uls_21_effect_01_SEED_${SEED}" 0
    Rscript --vanilla ife.R ${DATA_NAME} "rho_09_uls_21_effect_01_SEED_${SEED}" 10
    python cmgp.py ${DATA_NAME} "rho_09_uls_21_effect_01_SEED_${SEED}"
elif [ $3 = "icm" ]
then
    matlab -nodisplay -nodesktop -r "review_icm(${SEED},21,0.9,0.1,${DATA_NAME}); exit;"
elif [ $3 = "ltr" ]
then
    matlab -nodisplay -nodesktop -r "review_ltr(${SEED},21,0.9,0.1,${DATA_NAME}); exit;"
fi
