#!/bin/bash

# analysize results in synthetic experiments
# setting 1
MAXSEED=25
declare -a EFFECTS=(0.1)
declare -a ULS=(1000)
declare -a RHOS=(0.9999)

for uls in ${ULS[@]}; do
    for rho in ${RHOS[@]}; do
        for effect in ${EFFECTS[@]}; do
            Rscript --vanilla data/measures.R $MAXSEED $uls $rho $effect
        done
    done
done

for effect in ${EFFECTS[@]}; do
    Rscript --vanilla data/summary.R $MAXSEED $effect "${ULS[@]}" "${RHOS[@]}"
done

# setting 2
declare -a ULS=(21)
declare -a RHOS=(0.1 0.5 0.9)

for uls in ${ULS[@]}; do
    for rho in ${RHOS[@]}; do
        for effect in ${EFFECTS[@]}; do
            Rscript --vanilla data/measures.R $MAXSEED $uls $rho $effect
        done
    done
done

for effect in ${EFFECTS[@]}; do
    Rscript --vanilla data/summary.R $MAXSEED $effect "${ULS[@]}" "${RHOS[@]}"
done