#!/bin/bash

mkdir -p data/synthetic
mkdir -p results

# localnews 
matlab -nodisplay -nodesktop -r "localnews; exit;"

# sigact
matlab -nodisplay -nodesktop -r "sigact; exit;"

# synthetic experiments
# setting 1
MAXSEED=25
declare -a EFFECTS=(0.1)
declare -a ULS=(1000)
declare -a RHOS=(0.9999)

for SEED in $(seq 1 1 $MAXSEED); do
    for uls in ${ULS[@]}; do
        for rho in ${RHOS[@]}; do
            for effect in ${EFFECTS[@]}; do
                matlab -nodisplay -nodesktop -r "addpath('data');baseline(${SEED},${uls},${rho},${effect}); exit;"
            done
        done
    done
done

# setting 2
declare -a ULS=(21)
declare -a RHOS=(0.1 0.5 0.9)

for SEED in $(seq 1 1 $MAXSEED); do
    for uls in ${ULS[@]}; do
        for rho in ${RHOS[@]}; do
            for effect in ${EFFECTS[@]}; do
                matlab -nodisplay -nodesktop -r "addpath('data');baseline(${SEED},${uls},${rho},${effect}); exit;"
            done
        done
    done
done
